module.exports = {
    'unused-imports/no-unused-imports-ts': 'off',
    'unused-imports/no-unused-vars-ts': 'off',
    'eslint-comments/no-unlimited-disable': 'off',
    'eslint-comments/no-unused-disable': 'off',
    '@typescript-eslint/no-unsafe-assignment': 'off',
    '@typescript-eslint/no-unsafe-member-access': 'off',
    '@typescript-eslint/no-unsafe-call': 'off',
    'no-console': 'off',
    'no-unreachable': 'off',
    'import/prefer-default-export': 'off',
    'react-hooks/exhaustive-deps': 'warn',
    'import/order': 'off',
    'simple-import-sort/imports': 'off',
    'simple-import-sort/exports': 'off',
    'prettier/prettier': 'off',
    '@typescript-eslint/no-unused-vars': 'off',
    'spaced-comment': 'off',
};
